### ISSUE TITLE
delay on combo counter

### ISSUE THREAD

**Issue by DDMythical** [percyqaz/YAVSRG#17]
there is a noticeable delay between hitting a note and combo being added to the central counter.

likely something to do with the block around line 232 in screenPlay.cs

**Comment by DDMythical** [comment]
[8:00 PM] Percyqaz: it's caused by chord cohesion
[8:01 PM] Percyqaz: it waits 180ms to check for miss
[8:01 PM] Percyqaz: to give you time to hit it late
[8:01 PM] Percyqaz: it updates everything 180ms late

**Comment by percyqaz** [comment]
incoming workaround: move input handling from screenplay.cs to the score system code. needs to be done anyway

**Comment by percyqaz** [comment]
described changes have been put in place but delay will probably stay due to how live accuracy processing is designed

**Comment by percyqaz** [comment]
described changes are in and it's all done and dusted and fixed :)
