### ISSUE TITLE
Chart editor

### ISSUE THREAD

**Issue by percyqaz** [percyqaz/YAVSRG#38]
things it needs
- complementary editor metadata files containing working information including layering (color notes by layer), bookmarks, notes, selected snaps/view/time etc
- tabs for multiple charts open at once
- rough design with peer to peer collab in mind
- export to .osu .sm etc

things it doesn't need but will have need to be written up in the design doc

**Comment by percyqaz** [comment]
Change of plans
- [ ] interlude chart editing format (normal charts auto converted to this when loaded - can be exported to .yav, .osu, .sm - stored in same folder as song
- [ ] VBO support for NoteRenderer for both more transformation abilities but also embedding/shrinking into smaller panels for the editor so you can fit 10 key and also the UI
- [ ] now we're cracking

**Comment by percyqaz** [comment]
planned feature: editor filters
- gameplay modifiers run these filters so i will be porting existing gameplay mods to filters and then using that code
- filters can be run between two selected points in time or on selected notes
- filters can have a pop up dialog requesting more configuration

example filters
- places SV/column SV in patterns e.g. sawtooth waves, sine waves, note stutters etc
- pattern generators
- notes -> inverse LN
- placing BPM points to achieve certain snap colors for visual stuff

**Comment by percyqaz** [comment]
may be moved to an entirely separate project
- if so, said project will be able to communicate directly with interlude using something fancy so you can playtest with a button

**Comment by ExhaustedBiped** [comment]
> 
> 
> may be moved to an entirely separate project
> 
>     * if so, said project will be able to communicate directly with interlude using something fancy so you can playtest with a button

ArrowVortex is written in .NET I believe. This could be looked to for inspiration, no? Not too sure about complexity but a playtest system could be made by integrating a stripped down interlude player into the editor? Or having it move the saved file directly to the game path. IMO probably better to have it playable in one program to save computer resources.

**Comment by percyqaz** [comment]
this is going to be a separate project (for a handful of reasons - look forward to it :) )
