### ISSUE TITLE
Gameplay watcher system (i.e HP meters)

### ISSUE THREAD

**Issue by DDMythical** [percyqaz/YAVSRG#49]
alternate title: add a HP system

**Comment by percyqaz** [comment]
accuracy systems and hp systems will follow this framework (objects that watch your hit judgements while playing a chart and can have a variable reading/output (i.e current accuracy, current HP) that changes during the chart and can be displayed in the GUI.
already in progress

**Comment by percyqaz** [comment]
implemented
