### ISSUE TITLE
Load audio and background asynchronously

### ISSUE THREAD

**Issue by ZoeKaledi** [percyqaz/YAVSRG#50]
when any menu induces a chart change the background changes instantly, it should look nicer if theres a quick fade between the two a-la osu, or even a fade-in time like etterna, or just anything
idk

**Comment by percyqaz** [comment]
Already in progress

**Comment by percyqaz** [comment]
fade effect between backgrounds implemented :)

**Comment by percyqaz** [comment]
no longer planned as it is a lot of work for something currently minor enough to be left alone
