### ISSUE TITLE
The game crashed.

### ISSUE THREAD

**Issue by ATM415** [percyqaz/YAVSRG#60]
I was trying to play your game, but now, IT CRASH!!!

Can you help solve this problem, plz?

**Comment by percyqaz** [comment]
can you send a screenshot of the crash window or the log.txt in the folder? :)

**Comment by ATM415** [comment]
ok
![Screenshot_1](https://user-images.githubusercontent.com/52848807/62500202-49a66900-b79a-11e9-8125-58c2ef83dd47.png)

the log.txt is empty, and i cutted with Lightshot
(Sorry for the spanish text)

**Comment by percyqaz** [comment]
It seems that you do not have the .NET Framework 4.6.1 installed
You can install it from https://dotnet.microsoft.com/download/dotnet-framework/net461
(you only need the Runtime version)

Hopefully that fixes your issue
