### ISSUE TITLE
Make hitsounds?

### ISSUE THREAD

**Issue by DDMythical** [percyqaz/YAVSRG#9]
-- They are temporarily disabled. Look into this.

**Comment by percyqaz** [comment]
Renamed this issue to "Make hitsounds?". They lagged the game when i tried setting this up so i'll need to look into threading or a proper audio system for samples with bass to get this working.
This system is needed for interface sounds and stuff anyway so I have no choice but to look into this.

**Comment by percyqaz** [comment]
update: sound effect engine is in working order, i just have no sounds
sounds will be added for hitting notes / other stuff when i get round to it and skinning support is already in for sound effects.
